name: nextjs

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Setup Pages
        uses: actions/configure-pages@v3
        with:
          static_site_generator: next
      - name: Install dependencies
        run: npm install
      - name: Build with Next.js
        run: npm run build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./out

  redeploy:
    if: github.ref == 'refs/heads/main'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2

  mails-started:
    if: always()
    uses: tech1-io/tech1-reusable-ops/.github/workflows/mails-v2.yml@main
    secrets: inherit
    with:
      previous_job_status: started
      to: ${{ vars.EMAILS_ADMINS }}, ${{ vars.EMAILS_TEAM_WEBSITES }}

  mails-built:
    needs: [build]
    uses: tech1-io/tech1-reusable-ops/.github/workflows/mails-v2.yml@main
    secrets: inherit
    with:
      previous_job_status: built
      to: ${{ vars.EMAILS_ADMINS }}, ${{ vars.EMAILS_TEAM_WEBSITES }}

  mails-redeployed:
    needs: [redeploy]
    uses: tech1-io/tech1-reusable-ops/.github/workflows/mails-v2.yml@main
    secrets: inherit
    with:
      previous_job_status: redeployed
      to: ${{ vars.EMAILS_ADMINS }}, ${{ vars.EMAILS_TEAM_WEBSITES }}
